//! Cedar Falls / Waterloo opening cast. Inserts live in `seed`.

pub(crate) const GIFTS: &[(&str, &str, &str)] = &[
    ("gift_teaching", "Teaching", "spiritual"),
    ("gift_encouragement", "Encouragement", "spiritual"),
    ("gift_hospitality", "Hospitality", "spiritual"),
    ("gift_intercession", "Intercession", "spiritual"),
    ("gift_wisdom", "Wisdom", "spiritual"),
    ("gift_mercy", "Mercy", "spiritual"),
    ("gift_discernment", "Discernment", "spiritual"),
    ("gift_shepherding", "Shepherding", "pastoral"),
    ("gift_counseling", "Counseling", "pastoral"),
    ("gift_visitation", "Visitation", "pastoral"),
    ("gift_mentoring", "Mentoring", "pastoral"),
    ("gift_meals", "Meals", "practical"),
    ("gift_carpentry", "Carpentry & repairs", "practical"),
    ("gift_childcare", "Childcare", "practical"),
    ("gift_transport", "Transportation", "practical"),
    ("gift_medical", "Medical care", "practical"),
    ("gift_accounting", "Accounting", "practical"),
    ("gift_music", "Music", "creative"),
    ("gift_worship", "Worship leading", "creative"),
    ("gift_art", "Art", "creative"),
    ("gift_writing", "Writing", "creative"),
    ("gift_admin", "Administration", "logistical"),
    ("gift_translation", "Translation", "logistical"),
    ("gift_tech", "Technology", "logistical"),
];

pub(crate) const USERS: &[(&str, &str, &str, &str, &str, &str)] = &[
    (
        "user_miriam",
        "Miriam Cole",
        "miriam@gracecovenant.test",
        "Cedar Falls",
        "Iowa",
        "Pastor at Grace Covenant since 2014. Two kids, one very old dog. Happy to talk anytime.",
    ),
    (
        "user_daniel",
        "Daniel Okonkwo",
        "daniel@gracecovenant.test",
        "Cedar Falls",
        "Iowa",
        "High school chemistry teacher. Recovering from knee surgery right now, so I'm the one asking for help for once.",
    ),
    (
        "user_ruth",
        "Ruth Alvarez",
        "ruth@gracecovenant.test",
        "Cedar Falls",
        "Iowa",
        "I cook for a lot of people. Ask me about caldo.",
    ),
    (
        "user_samuel",
        "Samuel Wright",
        "samuel@stlukes.test",
        "Cedar Falls",
        "Iowa",
        "Rector at St. Luke's. Retired Army chaplain. I still make hospital visits most weeks.",
    ),
    (
        "user_james",
        "James Whitaker",
        "james@stlukes.test",
        "Cedar Falls",
        "Iowa",
        "Carpenter, 30 years. Ramps, doors, anything that wobbles. I have a truck.",
    ),
    (
        "user_keisha",
        "Keisha Brooks",
        "keisha@newmercy.test",
        "Waterloo",
        "Iowa",
        "Pastor at New Mercy in Waterloo. We meet in an old storefront on Sycamore Street. Come by.",
    ),
    (
        "user_elena",
        "Elena Vasquez",
        "elena@newmercy.test",
        "Waterloo",
        "Iowa",
        "Licensed counselor. I work in Spanish and English, including with hospitals and schools.",
    ),
    (
        "user_peter",
        "Peter Lang",
        "peter@cedarfalls.test",
        "Cedar Falls",
        "Iowa",
        "Just moved here from Des Moines for work. Two kids. I have a van and free Saturday mornings.",
    ),
];

pub(crate) const CHURCHES: &[(&str, &str, &str, &str, &str, &str, &str, &str)] = &[
    (
        "church_grace",
        "Grace Covenant Church",
        "Cedar Falls",
        "Iowa",
        "About 120 of us on a Sunday, on the corner of 12th and Main. Coffee after the service. Kids' classes during.",
        "Sundays 10:00 a.m.",
        "user_miriam",
        "grace-k2m9",
    ),
    (
        "church_luke",
        "St. Luke's Fellowship",
        "Cedar Falls",
        "Iowa",
        "An Episcopal parish downtown, founded 1881. Small and older now. We run the Tuesday food pantry with St. Patrick's.",
        "Sundays 9:00 a.m.",
        "user_samuel",
        "luke-p4r1",
    ),
    (
        "church_mercy",
        "New Mercy Community",
        "Waterloo",
        "Iowa",
        "A bilingual church in a storefront on Sycamore Street in Waterloo. We serve dinner every Wednesday night. Everyone's welcome.",
        "Sundays 11:00 a.m.",
        "user_keisha",
        "mercy-n8q2",
    ),
];

pub(crate) const MEMBERSHIPS: &[(&str, &str, &str, &str, &str)] = &[
    (
        "mem_grace_miriam",
        "church_grace",
        "user_miriam",
        "owner",
        "active",
    ),
    (
        "mem_grace_daniel",
        "church_grace",
        "user_daniel",
        "member",
        "active",
    ),
    (
        "mem_grace_ruth",
        "church_grace",
        "user_ruth",
        "member",
        "active",
    ),
    (
        "mem_grace_peter",
        "church_grace",
        "user_peter",
        "member",
        "pending_request",
    ),
    (
        "mem_luke_samuel",
        "church_luke",
        "user_samuel",
        "owner",
        "active",
    ),
    (
        "mem_luke_james",
        "church_luke",
        "user_james",
        "steward",
        "active",
    ),
    (
        "mem_mercy_keisha",
        "church_mercy",
        "user_keisha",
        "owner",
        "active",
    ),
    (
        "mem_mercy_elena",
        "church_mercy",
        "user_elena",
        "member",
        "active",
    ),
];

pub(crate) const MEMBER_GIFTS: &[(&str, &str, &str)] = &[
    (
        "user_miriam",
        "gift_shepherding",
        "Happy to meet for coffee or come to you.",
    ),
    (
        "user_miriam",
        "gift_wisdom",
        "Hard decisions, family stuff. I mostly listen.",
    ),
    (
        "user_daniel",
        "gift_encouragement",
        "I write notes and I remember birthdays.",
    ),
    (
        "user_daniel",
        "gift_intercession",
        "Send me a name. I keep a list.",
    ),
    (
        "user_ruth",
        "gift_meals",
        "Casseroles, caldo, and I clean up after.",
    ),
    (
        "user_ruth",
        "gift_hospitality",
        "There's always room at dinner. Sunday afternoons especially.",
    ),
    (
        "user_samuel",
        "gift_teaching",
        "Sunday preaching and a Wednesday Bible study.",
    ),
    (
        "user_samuel",
        "gift_visitation",
        "Hospital and home visits, most weeks.",
    ),
    (
        "user_james",
        "gift_carpentry",
        "Ramps, doors, leaky sinks, wobbly pews.",
    ),
    (
        "user_james",
        "gift_transport",
        "Pickup truck. Thursdays are usually open.",
    ),
    (
        "user_keisha",
        "gift_shepherding",
        "I check in on families after a hard month.",
    ),
    (
        "user_keisha",
        "gift_admin",
        "Meal trains, sign-up sheets, getting people organized.",
    ),
    (
        "user_elena",
        "gift_translation",
        "Spanish and English, including medical and legal terms.",
    ),
    (
        "user_elena",
        "gift_counseling",
        "Grief, marriage, and families who just arrived in the country.",
    ),
    (
        "user_peter",
        "gift_transport",
        "A van that fits a family plus boxes.",
    ),
    (
        "user_peter",
        "gift_childcare",
        "Two of my own. Fine with a loud room.",
    ),
];

pub(crate) const NEEDS: &[(&str, &str, &str, &str, &str, Option<&str>, &str, &str)] = &[
    (
        "need_meals",
        "church_grace",
        "user_miriam",
        "Dinners for the Okonkwo family",
        "Daniel is two weeks out from knee surgery. Ruth has covered two nights. We need five more dinners this week. Drop off at the side door any time after 5. They have a fridge on the porch.",
        Some("gift_meals"),
        "church",
        "open",
    ),
    (
        "need_ramp",
        "church_grace",
        "user_daniel",
        "Temporary ramp and a bathroom grab bar",
        "Three steps up to my front door and I can't do them on crutches yet. I need a temporary ramp and a grab bar by the shower. I'll buy the materials. Saturday morning works best.",
        Some("gift_carpentry"),
        "neighboring",
        "open",
    ),
    (
        "need_spanish",
        "church_grace",
        "user_miriam",
        "Spanish interpreter for Thursday counseling",
        "A couple from the neighborhood asked to meet with me Thursday at 6. Their English is limited and my Spanish is worse. I need an interpreter for about an hour, and it needs to stay private.",
        Some("gift_translation"),
        "neighboring",
        "open",
    ),
    (
        "need_prayer",
        "church_mercy",
        "user_keisha",
        "Prayer covering for two church-planting families",
        "Two families from our church moved to Dubuque and Mason City this summer to start new congregations. They're tired. If you'll commit to praying for one of them each week, reply and I'll send you a name.",
        Some("gift_intercession"),
        "body",
        "open",
    ),
    (
        "need_worship",
        "church_luke",
        "user_samuel",
        "A musician for Sunday the 29th",
        "Our organist and both guitarists are away at a retreat that weekend. We need someone to lead four hymns at the 9 a.m. service. Piano or guitar is fine. We'll send the hymn list ahead.",
        Some("gift_worship"),
        "neighboring",
        "open",
    ),
];
