//! Cedar Falls / Waterloo opening cast. Inserts live in `seed`.

pub(crate) const GIFTS: &[(&str, &str, &str)] = &[
    ("gift_teaching", "Teaching", "spiritual"),
    ("gift_encouragement", "Encouragement", "spiritual"),
    ("gift_hospitality", "Hospitality", "spiritual"),
    ("gift_intercession", "Intercession", "spiritual"),
    ("gift_wisdom", "Wisdom", "spiritual"),
    ("gift_mercy", "Mercy", "spiritual"),
    ("gift_discernment", "Discernment", "spiritual"),
    ("gift_shepherding", "Shepherding", "pastoral"),
    ("gift_counseling", "Counseling", "pastoral"),
    ("gift_visitation", "Visitation", "pastoral"),
    ("gift_mentoring", "Mentoring", "pastoral"),
    ("gift_meals", "Meals", "practical"),
    ("gift_carpentry", "Carpentry & repairs", "practical"),
    ("gift_childcare", "Childcare", "practical"),
    ("gift_transport", "Transportation", "practical"),
    ("gift_medical", "Medical care", "practical"),
    ("gift_accounting", "Accounting", "practical"),
    ("gift_music", "Music", "creative"),
    ("gift_worship", "Worship leading", "creative"),
    ("gift_art", "Art", "creative"),
    ("gift_writing", "Writing", "creative"),
    ("gift_admin", "Administration", "logistical"),
    ("gift_translation", "Translation", "logistical"),
    ("gift_tech", "Technology", "logistical"),
];

pub(crate) const USERS: &[(&str, &str, &str, &str, &str, &str)] = &[
    (
        "user_miriam",
        "Miriam Cole",
        "miriam@gracecovenant.test",
        "Cedar Falls",
        "Iowa",
        "Pastor of Grace Covenant. I keep watch so the flock can actually live as a body, not a Sunday audience.",
    ),
    (
        "user_daniel",
        "Daniel Okonkwo",
        "daniel@gracecovenant.test",
        "Cedar Falls",
        "Iowa",
        "Recovering from surgery and learning how to receive help without apology.",
    ),
    (
        "user_ruth",
        "Ruth Alvarez",
        "ruth@gracecovenant.test",
        "Cedar Falls",
        "Iowa",
        "I cook when people are tired. Tables are how I pray.",
    ),
    (
        "user_samuel",
        "Samuel Wright",
        "samuel@stlukes.test",
        "Cedar Falls",
        "Iowa",
        "Rector at St. Luke's. We would rather share a need than pretend we are sufficient.",
    ),
    (
        "user_james",
        "James Whitaker",
        "james@stlukes.test",
        "Cedar Falls",
        "Iowa",
        "Carpenter. If it is broken and a person has to live with it, call me.",
    ),
    (
        "user_keisha",
        "Keisha Brooks",
        "keisha@newmercy.test",
        "Waterloo",
        "Iowa",
        "Pastor at New Mercy. Waterloo and Cedar Falls are one valley. The body should act like it.",
    ),
    (
        "user_elena",
        "Elena Vasquez",
        "elena@newmercy.test",
        "Waterloo",
        "Iowa",
        "Bilingual counselor. I can sit with someone in Spanish or English and not rush them.",
    ),
    (
        "user_peter",
        "Peter Lang",
        "peter@cedarfalls.test",
        "Cedar Falls",
        "Iowa",
        "New in town. I have a van and Saturday mornings. Still looking for a church that will have me.",
    ),
];

pub(crate) const CHURCHES: &[(&str, &str, &str, &str, &str, &str, &str, &str)] = &[
    (
        "church_grace",
        "Grace Covenant Church",
        "Cedar Falls",
        "Iowa",
        "A neighborhood church that wants its gifts in motion during the week, not only listed in a bulletin.",
        "Sundays 10:00 a.m.",
        "user_miriam",
        "grace-k2m9",
    ),
    (
        "church_luke",
        "St. Luke's Fellowship",
        "Cedar Falls",
        "Iowa",
        "An older parish learning to ask neighboring churches for help instead of quietly running out of hands.",
        "Sundays 9:00 a.m.",
        "user_samuel",
        "luke-p4r1",
    ),
    (
        "church_mercy",
        "New Mercy Community",
        "Waterloo",
        "Iowa",
        "A storefront church across the river. We plant, cook, translate, and refuse to be an island.",
        "Sundays 11:00 a.m.",
        "user_keisha",
        "mercy-n8q2",
    ),
];

pub(crate) const MEMBERSHIPS: &[(&str, &str, &str, &str, &str)] = &[
    (
        "mem_grace_miriam",
        "church_grace",
        "user_miriam",
        "owner",
        "active",
    ),
    (
        "mem_grace_daniel",
        "church_grace",
        "user_daniel",
        "member",
        "active",
    ),
    (
        "mem_grace_ruth",
        "church_grace",
        "user_ruth",
        "member",
        "active",
    ),
    (
        "mem_grace_peter",
        "church_grace",
        "user_peter",
        "member",
        "pending_request",
    ),
    (
        "mem_luke_samuel",
        "church_luke",
        "user_samuel",
        "owner",
        "active",
    ),
    (
        "mem_luke_james",
        "church_luke",
        "user_james",
        "steward",
        "active",
    ),
    (
        "mem_mercy_keisha",
        "church_mercy",
        "user_keisha",
        "owner",
        "active",
    ),
    (
        "mem_mercy_elena",
        "church_mercy",
        "user_elena",
        "member",
        "active",
    ),
];

pub(crate) const MEMBER_GIFTS: &[(&str, &str, &str)] = &[
    (
        "user_miriam",
        "gift_shepherding",
        "Walking with people who are tired of performing church.",
    ),
    (
        "user_miriam",
        "gift_wisdom",
        "I listen a long time before I speak.",
    ),
    (
        "user_daniel",
        "gift_encouragement",
        "I write notes. I remember names.",
    ),
    (
        "user_daniel",
        "gift_intercession",
        "Especially in the night when I cannot sleep anyway.",
    ),
    (
        "user_ruth",
        "gift_meals",
        "Casseroles, caldo, and a clean kitchen afterward.",
    ),
    (
        "user_ruth",
        "gift_hospitality",
        "My table has two extra chairs on purpose.",
    ),
    (
        "user_samuel",
        "gift_teaching",
        "Lectionary preaching and quiet midweek study.",
    ),
    (
        "user_samuel",
        "gift_visitation",
        "Hospitals and kitchen tables.",
    ),
    (
        "user_james",
        "gift_carpentry",
        "Ramps, doors, leaky sinks, pews that wobble.",
    ),
    ("user_james", "gift_transport", "Truck and a free Thursday."),
    (
        "user_keisha",
        "gift_shepherding",
        "I will not let a family disappear after a hard month.",
    ),
    (
        "user_keisha",
        "gift_admin",
        "I can stand up a meal train before noon.",
    ),
    (
        "user_elena",
        "gift_translation",
        "Spanish and English, including medical words.",
    ),
    (
        "user_elena",
        "gift_counseling",
        "Grief, marriage, and the quiet panic of new immigrants.",
    ),
    (
        "user_peter",
        "gift_transport",
        "A van that fits a family plus boxes.",
    ),
    (
        "user_peter",
        "gift_childcare",
        "Two of my own. I am calm in a noisy room.",
    ),
];

pub(crate) const NEEDS: &[(&str, &str, &str, &str, &str, Option<&str>, &str, &str)] = &[
    (
        "need_meals",
        "church_grace",
        "user_miriam",
        "Meal train for the Okonkwo family",
        "Daniel is two weeks out of surgery. Ruth has already cooked twice. We need five more dinners this week — drop-off at the side door, no lingering required unless they ask.",
        Some("gift_meals"),
        "church",
        "open",
    ),
    (
        "need_ramp",
        "church_grace",
        "user_daniel",
        "Temporary ramp and a bathroom grab bar",
        "I can almost get into the house. Almost is how people fall. If you have a saw and an hour on Saturday, I will stay out of your way.",
        Some("gift_carpentry"),
        "neighboring",
        "open",
    ),
    (
        "need_spanish",
        "church_grace",
        "user_miriam",
        "Spanish interpreter for Thursday counseling",
        "A couple from our neighborhood asked for prayer and counsel. I need someone who can hold both languages without turning it into a spectacle.",
        Some("gift_translation"),
        "neighboring",
        "open",
    ),
    (
        "need_prayer",
        "church_mercy",
        "user_keisha",
        "Prayer covering for two church-planting families",
        "They are tired and far from their sending churches. This is open to the whole body — a name, a time, and you keep it.",
        Some("gift_intercession"),
        "body",
        "open",
    ),
    (
        "need_worship",
        "church_luke",
        "user_samuel",
        "Someone to lead sung prayer on the 29th",
        "Our musicians are at a retreat. We would rather borrow a neighbor than press play on a laptop.",
        Some("gift_worship"),
        "neighboring",
        "open",
    ),
];
